### ISSUE TITLE
getter for scoped elements

### ISSUE THREAD

**Issue by 3052** [Eyevinn/dash-mpd#18]
some elements like `ContentProtection` can exist under `AdaptationSet`:

<https://github.com/Eyevinn/dash-mpd/blob/f7748ed6f483bebe06795fb0c03c41f856809093/mpd/testdata/go-dash-fixtures/live_profile.mpd#L4-L5>

but they can also exist under `Representation`:

https://github.com/Eyevinn/dash-mpd/blob/f7748ed6f483bebe06795fb0c03c41f856809093/mpd/mpd.go#L380-L400

I think it would be helpful if we had a getter under `RepresentationType` or `RepresentationBaseType` that would return its own `ContentProtections` if `len()>=1`, otherwise return the parents `ContentProtections`

**Comment by 3052** [comment]
thinking about it more, maybe a better option might be to add a setter method similar to this:

https://github.com/Eyevinn/dash-mpd/blob/f7748ed6f483bebe06795fb0c03c41f856809093/mpd/parents.go#L46-L53

**Comment by tobbee** [comment]
@3052  Thanks for your suggestion of adding a getter that automatically looks in the parent if not set on the representation. I can certainly add that. 

However, you mention a "setter" method in your second comment. Could you elaborate how you would like to do that for ContentProtection?

**Comment by 3052** [comment]
a better option might be, in `MPDFromBytes` and similar, to run a setter function similar to `SetParents`. this function would check the ContentProtection value of the child, and if length zero would set the value to the parent. this way you no longer need a getter function, because the child would always have the expected value. just a different approach.

**Comment by 3052** [comment]
OK I agree. the PR is good, but we might also need methods for  `mimeType` and `SegmentTemplate`, since those can also exist in the parent instead of the child

**Comment by tobbee** [comment]
Sure. I added these guys as well
