### ISSUE TITLE
Keep the following namespace attributes in MPD element

### ISSUE THREAD

**Issue by Murmur** [Eyevinn/dash-mpd#21]
See this issue in Livesim2 and example mpd url.
https://github.com/Dash-Industry-Forum/livesim2/issues/140#issuecomment-1833904473

I would like to see the following attributes be kept in `<MPD>` parent element. Most of them relate to DRM `<ContentProtection>` use.
* xmlns:cenc="urn:mpeg:cenc:2013"
* xmlns:ck="http://dashif.org/guidelines/clearKey"
* xmlns:dashif="https://dashif.org/" 
* xmlns:mas="urn:marlin:mas:1-0:services:schemas:mpd" 
* xmlns:mspr="urn:microsoft:playready"
* xmlns:xlink="http://www.w3.org/1999/xlink"

Library should keep an existing attributes in a livesim2 vod-to-live manifest manipulation.

**Comment by tobbee** [comment]
Its is actually not possible to put the name spaces on the top level, but they will be defined inside the relevant element.




There is a lot of example MPDs with various name spaces that are supported transparently in the mod/testdata catalog.
These examples are essentially unchanged by the MPD processing (unmarshal and marshal from XML to XML):

The cenc and mspr name spaces are in the testdata example  "https://github.com/Eyevinn/dash-mpd/blob/main/mpd/testdata/go-dash-fixtures/hbbtv_profile.mpd".

Xlink is in the example https://github.com/Eyevinn/dash-mpd/blob/main/mpd/testdata/schema-mpds/example_G20.mpd

From the above, I would therefore put the status as:

- [x] xmlns:cenc="urn:mpeg:cenc:2013"
- [ ] xmlns:ck="http://dashif.org/guidelines/clearKey"
- [ ] xmlns:dashif="https://dashif.org/"
- [ ] xmlns:mas="urn:marlin:mas:1-0:services:schemas:mpd"
- [x] xmlns:mspr="urn:microsoft:playready"
- [x] xmlns:xlink="http://www.w3.org/1999/xlink"

I think one should add  similar examples for the new name spaces, maybe in a new category: "name-spaces" or similar.
Could you provide examples on how the three missing ones would be used?

In any case, I think there will be limitation in the sense that the namespaces may not remain on the top level if you specify them there, but they may propagate down to where they are used.

**Comment by tobbee** [comment]
With #23  all the elements are supported. The namespaces are moved to the highest level they are used, but that should be fine from an XML equivalence point of view. That is actually tested since the test vector has the name spaces at the top level.
